<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-IREDREU" name="parallel.grid.roughWork.TestCase6" tests="5" failures="0" timestamp="2020-04-23T19:25:30 BST" time="45.640" errors="2">
  <testcase name="logIn" time="16.139" classname="parallel.grid.roughWork.TestCase6"/>
  <system-out/>
  <testcase name="logIn" time="0.007" classname="parallel.grid.roughWork.TestCase6">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at parallel.grid.roughWork.BaseTest.openBrowser(BaseTest.java:53)
at parallel.grid.roughWork.TestCase6.logIn(TestCase6.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- logIn -->
  <system-out/>
  <testcase name="logIn" time="0.004" classname="parallel.grid.roughWork.TestCase6">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at parallel.grid.roughWork.BaseTest.openBrowser(BaseTest.java:53)
at parallel.grid.roughWork.TestCase6.logIn(TestCase6.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- logIn -->
  <system-out/>
  <testcase name="logIn" time="14.480" classname="parallel.grid.roughWork.TestCase6"/>
  <system-out/>
  <testcase name="logIn" time="15.010" classname="parallel.grid.roughWork.TestCase6"/>
  <system-out/>
</testsuite> <!-- parallel.grid.roughWork.TestCase6 -->
